spring:
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://db-who.c2dkfbc2qp0h.ap-northeast-2.rds.amazonaws.com:3306/dbwho
    username: admin
    password: dbals3319
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false #default 는 true, 개발 시에는 false 로 설정

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    #    hibernate.hbm2ddl.auto: update
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
      logging.level:
        org.hibernate.SQL: debug
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800


