spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whoyaong?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800